#!/usr/bin/env python

import sys

fname = sys.argv[-1]

with open(fname, 'r') as f:
    lines = f.readlines()

with open(fname, 'w') as f:
    for line in lines:
        f.write(line.rstrip() + "\n")
